[workspace]
members=[
  "schotter1",
  "schotter2",
  "schotter3",
  "schotter4",
  "schotter4-hue",
  "test1"
]
resolver="2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
